//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageExplorer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PackageExplorer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors:.
        /// </summary>
        internal static string Dialog_CreatedByLabel {
            get {
                return ResourceManager.GetString("Dialog_CreatedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies:.
        /// </summary>
        internal static string Dialog_DependenciesLabel {
            get {
                return ResourceManager.GetString("Dialog_DependenciesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Dependency:.
        /// </summary>
        internal static string Dialog_DevelopmentDependencyLabel {
            get {
                return ResourceManager.GetString("Dialog_DevelopmentDependencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading package {0} {1}.
        /// </summary>
        internal static string Dialog_DownloadingPackage {
            get {
                return ResourceManager.GetString("Dialog_DownloadingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string Dialog_Errors {
            get {
                return ResourceManager.GetString("Dialog_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework Assembly References:.
        /// </summary>
        internal static string Dialog_FrameworkAssembliesLabel {
            get {
                return ResourceManager.GetString("Dialog_FrameworkAssembliesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: Luan Nguyen (@dotnetjunky). For more information, visit http://nuget.codeplex.com..
        /// </summary>
        internal static string Dialog_HelpAbout {
            get {
                return ResourceManager.GetString("Dialog_HelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        internal static string Dialog_IdLabel {
            get {
                return ResourceManager.GetString("Dialog_IdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Dialog_Information {
            get {
                return ResourceManager.GetString("Dialog_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package URL {0} is invalid and can not be opened..
        /// </summary>
        internal static string Dialog_InvalidPackageUrl {
            get {
                return ResourceManager.GetString("Dialog_InvalidPackageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Dialog_LanguageLabel {
            get {
                return ResourceManager.GetString("Dialog_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min client version:.
        /// </summary>
        internal static string Dialog_MinVersionLabel {
            get {
                return ResourceManager.GetString("Dialog_MinVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Information.
        /// </summary>
        internal static string Dialog_MoreInfo {
            get {
                return ResourceManager.GetString("Dialog_MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Dependencies.
        /// </summary>
        internal static string Dialog_NoDependencyLabel {
            get {
                return ResourceManager.GetString("Dialog_NoDependencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supported files|*.nupkg;*.nuspec|NuGet package file (*.nupkg)|*.nupkg|NuSpec file (*.nuspec)|*.nuspec.
        /// </summary>
        internal static string Dialog_OpenFileFilter {
            get {
                return ResourceManager.GetString("Dialog_OpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owners:.
        /// </summary>
        internal static string Dialog_OwnersLabel {
            get {
                return ResourceManager.GetString("Dialog_OwnersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher:.
        /// </summary>
        internal static string Dialog_PublisherLabel {
            get {
                return ResourceManager.GetString("Dialog_PublisherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Abuse.
        /// </summary>
        internal static string Dialog_ReportAbuse {
            get {
                return ResourceManager.GetString("Dialog_ReportAbuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository Signatures:.
        /// </summary>
        internal static string Dialog_RepositorySignatures {
            get {
                return ResourceManager.GetString("Dialog_RepositorySignatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires License Acceptance:.
        /// </summary>
        internal static string Dialog_RequireLicenseLabel {
            get {
                return ResourceManager.GetString("Dialog_RequireLicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your changes?.
        /// </summary>
        internal static string Dialog_SaveQuestion {
            get {
                return ResourceManager.GetString("Dialog_SaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviceable:.
        /// </summary>
        internal static string Dialog_ServiceableLabel {
            get {
                return ResourceManager.GetString("Dialog_ServiceableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external url wants to add a publish source to NuGet Package Explorer.
        ///
        ///Do you want to add &apos;{0}&apos; to the list of package publish sources?.
        /// </summary>
        internal static string Dialog_SetActivePackagePublishSource {
            get {
                return ResourceManager.GetString("Dialog_SetActivePackagePublishSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        internal static string Dialog_ShowDetails {
            get {
                return ResourceManager.GetString("Dialog_ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Validation:.
        /// </summary>
        internal static string Dialog_SignatureValidation {
            get {
                return ResourceManager.GetString("Dialog_SignatureValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags:.
        /// </summary>
        internal static string Dialog_TagLabel {
            get {
                return ResourceManager.GetString("Dialog_TagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet Package Explorer.
        /// </summary>
        internal static string Dialog_Title {
            get {
                return ResourceManager.GetString("Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string Dialog_TitleLabel {
            get {
                return ResourceManager.GetString("Dialog_TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Results:.
        /// </summary>
        internal static string Dialog_ValidationResult {
            get {
                return ResourceManager.GetString("Dialog_ValidationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Validation Results.
        /// </summary>
        internal static string Dialog_ValidationResultTitle {
            get {
                return ResourceManager.GetString("Dialog_ValidationResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string Dialog_VersionLabel {
            get {
                return ResourceManager.GetString("Dialog_VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View License Terms.
        /// </summary>
        internal static string Dialog_ViewLicense {
            get {
                return ResourceManager.GetString("Dialog_ViewLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        internal static string Dialog_Warnings {
            get {
                return ResourceManager.GetString("Dialog_Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add the file &apos;{0}&apos; to &apos;{1}&apos; folder instead?.
        /// </summary>
        internal static string MoveContentFileToFolder {
            get {
                return ResourceManager.GetString("MoveContentFileToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet does not do anything special with files at the package root. The extension of this file indicates that it is intended to be placed in the &apos;{0}&apos; folder. .
        /// </summary>
        internal static string MoveContentFileToFolderExplanation {
            get {
                return ResourceManager.GetString("MoveContentFileToFolderExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not framework specific).
        /// </summary>
        internal static string NoFxDependencyGroup {
            get {
                return ResourceManager.GetString("NoFxDependencyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network connection is not detected..
        /// </summary>
        internal static string NoNetworkConnection {
            get {
                return ResourceManager.GetString("NoNetworkConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download package correctly. The contents of the package could not be verified..
        /// </summary>
        internal static string PackageContentsVerifyError {
            get {
                return ResourceManager.GetString("PackageContentsVerifyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no contents or dependencies in the package..
        /// </summary>
        internal static string PackageHasNoFile {
            get {
                return ResourceManager.GetString("PackageHasNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to {0}.
        /// </summary>
        internal static string ProxyConnectToMessage {
            get {
                return ResourceManager.GetString("ProxyConnectToMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string Validation_Invalid {
            get {
                return ResourceManager.GetString("Validation_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted.
        /// </summary>
        internal static string Validation_Trusted {
            get {
                return ResourceManager.GetString("Validation_Trusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uknown.
        /// </summary>
        internal static string Validation_Unknown {
            get {
                return ResourceManager.GetString("Validation_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untrusted.
        /// </summary>
        internal static string Validation_Untrusted {
            get {
                return ResourceManager.GetString("Validation_Untrusted", resourceCulture);
            }
        }
    }
}
