//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageExplorer.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int FontSize
        {
            get
            {
                return ((int)(this["FontSize"]));
            }
            set
            {
                this["FontSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public double ContentViewerHeight
        {
            get
            {
                return ((double)(this["ContentViewerHeight"]));
            }
            set
            {
                this["ContentViewerHeight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nuget.org/api/v2/")]
        public string PackageSource
        {
            get
            {
                return ((string)(this["PackageSource"]));
            }
            set
            {
                this["PackageSource"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WindowPlacement
        {
            get
            {
                return ((string)(this["WindowPlacement"]));
            }
            set
            {
                this["WindowPlacement"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PublishPrivateKey
        {
            get
            {
                return ((string)(this["PublishPrivateKey"]));
            }
            set
            {
                this["PublishPrivateKey"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MruFiles
        {
            get
            {
                return ((global::System.Collections.Specialized.StringCollection)(this["MruFiles"]));
            }
            set
            {
                this["MruFiles"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MruPackageSources
        {
            get
            {
                return ((global::System.Collections.Specialized.StringCollection)(this["MruPackageSources"]));
            }
            set
            {
                this["MruPackageSources"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nuget.org")]
        public string PublishPackageLocation
        {
            get
            {
                return ((string)(this["PublishPackageLocation"]));
            }
            set
            {
                this["PublishPackageLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("630")]
        public double PackageChooserDialogWidth
        {
            get
            {
                return ((double)(this["PackageChooserDialogWidth"]));
            }
            set
            {
                this["PackageChooserDialogWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("450")]
        public double PackageChooserDialogHeight
        {
            get
            {
                return ((double)(this["PackageChooserDialogHeight"]));
            }
            set
            {
                this["PackageChooserDialogHeight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFirstTime
        {
            get
            {
                return ((bool)(this["IsFirstTime"]));
            }
            set
            {
                this["IsFirstTime"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection PublishPackageSources
        {
            get
            {
                return ((global::System.Collections.Specialized.StringCollection)(this["PublishPackageSources"]));
            }
            set
            {
                this["PublishPackageSources"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public double PackageContentHeight
        {
            get
            {
                return ((double)(this["PackageContentHeight"]));
            }
            set
            {
                this["PackageContentHeight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTaskShortcuts
        {
            get
            {
                return ((bool)(this["ShowTaskShortcuts"]));
            }
            set
            {
                this["ShowTaskShortcuts"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WordWrap
        {
            get
            {
                return ((bool)(this["WordWrap"]));
            }
            set
            {
                this["WordWrap"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowLineNumbers
        {
            get
            {
                return ((bool)(this["ShowLineNumbers"]));
            }
            set
            {
                this["ShowLineNumbers"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PublishAsUnlisted
        {
            get
            {
                return ((bool)(this["PublishAsUnlisted"]));
            }
            set
            {
                this["PublishAsUnlisted"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowPrereleasePackages
        {
            get
            {
                return ((bool)(this["ShowPrereleasePackages"]));
            }
            set
            {
                this["ShowPrereleasePackages"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SolicitInstallNpeForWin8
        {
            get
            {
                return ((bool)(this["SolicitInstallNpeForWin8"]));
            }
            set
            {
                this["SolicitInstallNpeForWin8"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFirstTimeAfterMigrate
        {
            get
            {
                return ((bool)(this["IsFirstTimeAfterMigrate"]));
            }
            set
            {
                this["IsFirstTimeAfterMigrate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoLoadPackages
        {
            get
            {
                return ((bool)(this["AutoLoadPackages"]));
            }
            set
            {
                this["AutoLoadPackages"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string SigningCertificate
        {
            get
            {
                return ((string)(this["SigningCertificate"]));
            }
            set
            {
                this["SigningCertificate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TimestampServer
        {
            get
            {
                return ((string)(this["TimestampServer"]));
            }
            set
            {
                this["TimestampServer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string SigningHashAlgorithmName
        {
            get
            {
                return ((string)(this["SigningHashAlgorithmName"]));
            }
            set
            {
                this["SigningHashAlgorithmName"] = value;
            }
        }
    }
}
