<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Uno\Api\Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" VersionOverride="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" VersionOverride="17.14.1" />
    <PackageReference Include="xunit" VersionOverride="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" VersionOverride="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
