//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageExplorerViewModel {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PackageExplorerViewModel.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse ähnelt.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Certificate ähnelt.
        /// </summary>
        public static string Certificate {
            get {
                return ResourceManager.GetString("Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Certificate Info ähnelt.
        /// </summary>
        public static string CertificateInfo {
            get {
                return ResourceManager.GetString("CertificateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Certificate Store ähnelt.
        /// </summary>
        public static string CertificateStore {
            get {
                return ResourceManager.GetString("CertificateStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Provide the code signing certificate for signing the package. ähnelt.
        /// </summary>
        public static string ChooseCertificate_Description {
            get {
                return ResourceManager.GetString("ChooseCertificate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose a Certificate for Package Signing ähnelt.
        /// </summary>
        public static string ChooseCertificate_Title {
            get {
                return ResourceManager.GetString("ChooseCertificate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete &apos;{0}&apos;? ähnelt.
        /// </summary>
        public static string ConfirmToDeleteContent {
            get {
                return ResourceManager.GetString("ConfirmToDeleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deleted file or folder is not recoverable. ähnelt.
        /// </summary>
        public static string ConfirmToDeleteContent_Title {
            get {
                return ResourceManager.GetString("ConfirmToDeleteContent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete this plugin? ähnelt.
        /// </summary>
        public static string ConfirmToDeletePlugin {
            get {
                return ResourceManager.GetString("ConfirmToDeletePlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to replace the existing file &apos;{0}&apos;? ähnelt.
        /// </summary>
        public static string ConfirmToReplaceExsitingFile {
            get {
                return ResourceManager.GetString("ConfirmToReplaceExsitingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is already a file with the same name in this folder. ähnelt.
        /// </summary>
        public static string ConfirmToReplaceExsitingFile_Title {
            get {
                return ResourceManager.GetString("ConfirmToReplaceExsitingFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to replace existing file &apos;{0}&apos; on disk? ähnelt.
        /// </summary>
        public static string ConfirmToReplaceFile {
            get {
                return ResourceManager.GetString("ConfirmToReplaceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is already a file with the same name in this location. ähnelt.
        /// </summary>
        public static string ConfirmToReplaceFile_Title {
            get {
                return ResourceManager.GetString("ConfirmToReplaceFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connecting to package source... ähnelt.
        /// </summary>
        public static string ConnectingMessage {
            get {
                return ResourceManager.GetString("ConnectingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to save your changes? ähnelt.
        /// </summary>
        public static string Dialog_SaveQuestion {
            get {
                return ResourceManager.GetString("Dialog_SaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NuGet Package Explorer ähnelt.
        /// </summary>
        public static string Dialog_Title {
            get {
                return ResourceManager.GetString("Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The operation cannot be completed because the edit form has some invalid input. ähnelt.
        /// </summary>
        public static string EditFormHasInvalidInput {
            get {
                return ResourceManager.GetString("EditFormHasInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This package has been exported successfully. ähnelt.
        /// </summary>
        public static string ExportPackageSuccess {
            get {
                return ResourceManager.GetString("ExportPackageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The new file has the same name as another folder. ähnelt.
        /// </summary>
        public static string FileNameConflictWithExistingDirectory {
            get {
                return ResourceManager.GetString("FileNameConflictWithExistingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hash Algorithm Name ähnelt.
        /// </summary>
        public static string HashAlgorithName {
            get {
                return ResourceManager.GetString("HashAlgorithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading... ähnelt.
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No network connection is detected. ähnelt.
        /// </summary>
        public static string NoNetworkConnection {
            get {
                return ResourceManager.GetString("NoNetworkConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opening this file can potentially harm your computer. Do you want to continue? ähnelt.
        /// </summary>
        public static string OpenExecutableScriptWarning {
            get {
                return ResourceManager.GetString("OpenExecutableScriptWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file &apos;{0}&apos; is executable. ähnelt.
        /// </summary>
        public static string OpenExecutableScriptWarning_Title {
            get {
                return ResourceManager.GetString("OpenExecutableScriptWarning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to generate package due to this error: ähnelt.
        /// </summary>
        public static string PackageCreationFailed {
            get {
                return ResourceManager.GetString("PackageCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password incorrect ähnelt.
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password required ähnelt.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file &apos;{0}&apos; was either renamed or deleted from its physical location. It will now be removed from the package. ähnelt.
        /// </summary>
        public static string PhysicalFileMissing {
            get {
                return ResourceManager.GetString("PhysicalFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die *** The plugin that registers to read this file type fails to read the content of this file. *** ähnelt.
        /// </summary>
        public static string PluginFailToReadContent {
            get {
                return ResourceManager.GetString("PluginFailToReadContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is another file or folder with the same name as &apos;{0}&apos;. ähnelt.
        /// </summary>
        public static string RenameCausesNameCollison {
            get {
                return ResourceManager.GetString("RenameCausesNameCollison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Certificate ähnelt.
        /// </summary>
        public static string SelectCertificate {
            get {
                return ResourceManager.GetString("SelectCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign ähnelt.
        /// </summary>
        public static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signing package... ähnelt.
        /// </summary>
        public static string SigningPackage {
            get {
                return ResourceManager.GetString("SigningPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove signature and signing package... ähnelt.
        /// </summary>
        public static string SigningPackageAndRemoveSignature {
            get {
                return ResourceManager.GetString("SigningPackageAndRemoveSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign Package ähnelt.
        /// </summary>
        public static string SignPackage {
            get {
                return ResourceManager.GetString("SignPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timestamp Server ähnelt.
        /// </summary>
        public static string TimestampServer {
            get {
                return ResourceManager.GetString("TimestampServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die *** The format of this file is not supported. *** ähnelt.
        /// </summary>
        public static string UnsupportedFormatMessage {
            get {
                return ResourceManager.GetString("UnsupportedFormatMessage", resourceCulture);
            }
        }
    }
}
